### ISSUE TITLE
Wrong capitalization of includes

### ISSUE THREAD

**Issue by yaqwsx** [appliedprocrastination/OpenMacroRail#1]
There is a wrong capitalization of the include:

https://github.com/appliedprocrastination/OpenMacroRail/blob/9ee4d82cbd983a8763d609db4e54273fdf9d897c/OpenMacroRail_Arduino/OpenMacroRail_Arduino.ino#L97

It causes problems on case-sensitive systems.

**Comment by SimenZhor** [comment]
Thanks for reporting this @yaqwsx 😃
